### ISSUE TITLE
JSX Type Inference

### ISSUE THREAD

**Issue by kamal-alshair-iris** [hrastnik/mobx-easy-form#1]
In TSX files where this code is, you're able to do createField<ValueType, ParsedType>. The documentation does not appear to provide a JSX equivalent for this. Also in TSX files, validationSchema attributes error out.

**Comment by hrastnik** [comment]
I've released version 1.0.9 with improved type inference where this issue should be fixed.

The `ParsedType` will be automatically inferred based on the validationSchema type.

Let me know if there's any more issues.
